module.exports = {
  variables: { colors: true },
  aspectRatios: { mq: true },
  backgroundColors: { colors: true, alpha: true },
  backgroundSize: { mq: true },
  backgroundPosition: { mq: true },
  borders: { mq: true },
  borderColors: { colors: true },
  borderRadius: { mq: true },
  borderStyle: { mq: true },
  borderWidths: { mq: true },
  boxShadow: { mq: true },
  boxSizing: {},
  code: {},
  colors: { colors: true },
  spacing: { mq: true },
  coordinates: { mq: true },
  clears: { mq: true },
  display: { mq: true },
  flexbox: { mq: true },
  floats: { mq: true },
  fontFamily: {},
  fontStyle: { mq: true },
  fontWeight: { mq: true },
  forms: {},
  debugChildren: {},
  debugGrid: {},
  links: {},
  lists: {},
  heights: { mq: true },
  skins: { colors: true },
  skinsPseudo: { colors: true },
  images: {},
  letterSpacing: { mq: true },
  lineHeight: { mq: true },
  maxWidths: { mq: true },
  normalize: {},
  nested: {},
  hovers: {},
  opacity: { mq: true },
  rotations: { mq: true },
  outlines: { mq: true },
  overflow: { mq: true },
  position: { mq: true },
  tables: {},
  textDecoration: { mq: true },
  textAlign: { mq: true },
  textTransform: { mq: true },
  verticalAlign: {},
  typeScale: { mq: true },
  typography: { mq: true },
  utilities: {},
  visibility: { mq: true },
  whiteSpace: { mq: true },
  widths: { mq: true },
  zIndex: {}
}
